### ISSUE TITLE
Is the original Perl script available somewhere?

### ISSUE THREAD

**Issue by andrewpollock** [istathar/slashtime#4]
Hey Andrew,

I live my life SSHed into Linux from Chrome OS, and so I'd like to still use your original Perl script over a GUI tool. I've been cargo culting a copy around various Linux boxes I dwell in, but I was wondering if there was an authoritative source I could be pulling from instead?

regards

Andrew

**Comment by istathar** [comment]
Gawd. I don't think I even have it anymore. I've been meaning to recreate a command-line version, but if you've got a Perl version handy (@stewartsmith might have one to compare) that would be neat.

**Comment by andrewpollock** [comment]
Turns out there's always the [Wayback Machine](https://web.archive.org/web/20081007040334/http://research.operationaldynamics.com/projects/scripts/slashtime/slashtime.pl)
